import fs from 'node:fs/promises';
import path from 'node:path';
import { prisma } from '../config/prisma.js';
import { publicUser } from '../utils/auth.js';
import { env } from '../config/env.js';

const clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined));
const dateOrNull = (v) => v ? new Date(v) : null;

export async function selectBusiness(req, res) {
  const businessType = Number(req.body.businessType);
  if (![0, 1].includes(businessType)) return res.status(400).json({ message: 'businessType must be 0 (Pharmacy) or 1 (Distributor).' });
  const user = await prisma.user.update({ where: { id: req.user.id }, data: { businessType, onboardingStatus: 'BUSINESS_INFO_PENDING' } });
  res.json({ message: 'Business type selected.', businessType, user: publicUser(user) });
}

export async function getBusinessType(req, res) { res.json({ businessType: req.user.businessType, user: publicUser(req.user) }); }

export async function saveLocation(req, res) {
  const d = req.body;
  const location = await prisma.businessLocation.create({ data: { userId: req.user.id, locationType: Number(d.locationType || 0), warehouseName: d.warehouseName, contactPerson: d.contactPerson, contactNumber: d.contactNumber, latitude: d.latitude == null ? null : Number(d.latitude), longitude: d.longitude == null ? null : Number(d.longitude), accuracy: d.accuracy == null ? null : Number(d.accuracy), formattedAddress: d.formattedAddress, addressLine1: d.addressLine1, addressLine2: d.addressLine2, city: d.city, state: d.state, country: d.country, pincode: d.pincode, isPrimary: Boolean(d.isPrimary) } });
  if (location.isPrimary) await prisma.businessLocation.updateMany({ where: { userId: req.user.id, id: { not: location.id } }, data: { isPrimary: false } });
  res.status(201).json(location);
}
export async function getLocations(req, res) { res.json(await prisma.businessLocation.findMany({ where: { userId: req.user.id }, orderBy: [{ isPrimary: 'desc' }, { createdAt: 'asc' }] })); }
export async function getLocation(req, res) { const x = await prisma.businessLocation.findFirst({ where: { id: req.params.id, userId: req.user.id } }); if (!x) return res.status(404).json({ message: 'Location not found.' }); res.json(x); }
export async function updateLocation(req, res) { const existing = await prisma.businessLocation.findFirst({ where: { id: req.params.id, userId: req.user.id } }); if (!existing) return res.status(404).json({ message: 'Location not found.' }); const d=req.body; const x=await prisma.businessLocation.update({where:{id:existing.id},data:{...clean({locationType:d.locationType == null ? undefined : Number(d.locationType),warehouseName:d.warehouseName,contactPerson:d.contactPerson,contactNumber:d.contactNumber,latitude:d.latitude == null ? undefined : Number(d.latitude),longitude:d.longitude == null ? undefined : Number(d.longitude),accuracy:d.accuracy == null ? undefined : Number(d.accuracy),formattedAddress:d.formattedAddress,addressLine1:d.addressLine1,addressLine2:d.addressLine2,city:d.city,state:d.state,country:d.country,pincode:d.pincode,isPrimary:d.isPrimary == null ? undefined : Boolean(d.isPrimary)})}}); if(x.isPrimary) await prisma.businessLocation.updateMany({where:{userId:req.user.id,id:{not:x.id}},data:{isPrimary:false}}); res.json(x); }
export async function deleteLocation(req, res) { const r=await prisma.businessLocation.deleteMany({where:{id:req.params.id,userId:req.user.id}}); if(!r.count) return res.status(404).json({message:'Location not found.'}); res.json({message:'Location deleted.'}); }

export async function saveDistributor(req,res){ const d=req.body; const x=await prisma.distributorDetails.upsert({where:{userId:req.user.id},create:{userId:req.user.id,companyName:d.companyName || d.businessName || '',gstNumber:d.gstNumber,drugLicenseNumber:d.drugLicenseNumber,drugLicenseExpiryDate:dateOrNull(d.drugLicenseExpiryDate),panNumber:d.panNumber,distributorRegistrationNumber:d.distributorRegistrationNumber,serviceCities:d.serviceCities,minimumOrderValue:d.minimumOrderValue==null?null:Number(d.minimumOrderValue),isCreditAvailable:Boolean(d.isCreditAvailable),creditDays:d.creditDays==null?null:Number(d.creditDays),maximumCreditLimit:d.maximumCreditLimit==null?null:Number(d.maximumCreditLimit),hasOwnDelivery:Boolean(d.hasOwnDelivery),deliveryVehicleTypes:d.deliveryVehicleTypes,warehouseOpenTime:d.warehouseOpenTime,warehouseCloseTime:d.warehouseCloseTime,is24x7:Boolean(d.is24x7),emergencyContactNumber:d.emergencyContactNumber,contactPerson:d.contactPerson,contactNumber:d.contactNumber,email:d.email,formattedAddress:d.formattedAddress,latitude:d.latitude==null?null:Number(d.latitude),longitude:d.longitude==null?null:Number(d.longitude)},update:{companyName:d.companyName || d.businessName || '',gstNumber:d.gstNumber,drugLicenseNumber:d.drugLicenseNumber,drugLicenseExpiryDate:dateOrNull(d.drugLicenseExpiryDate),panNumber:d.panNumber,distributorRegistrationNumber:d.distributorRegistrationNumber,serviceCities:d.serviceCities,minimumOrderValue:d.minimumOrderValue==null?null:Number(d.minimumOrderValue),isCreditAvailable:Boolean(d.isCreditAvailable),creditDays:d.creditDays==null?null:Number(d.creditDays),maximumCreditLimit:d.maximumCreditLimit==null?null:Number(d.maximumCreditLimit),hasOwnDelivery:Boolean(d.hasOwnDelivery),deliveryVehicleTypes:d.deliveryVehicleTypes,warehouseOpenTime:d.warehouseOpenTime,warehouseCloseTime:d.warehouseCloseTime,is24x7:Boolean(d.is24x7),emergencyContactNumber:d.emergencyContactNumber,contactPerson:d.contactPerson,contactNumber:d.contactNumber,email:d.email,formattedAddress:d.formattedAddress,latitude:d.latitude==null?null:Number(d.latitude),longitude:d.longitude==null?null:Number(d.longitude)}}); await prisma.user.update({where:{id:req.user.id},data:{onboardingStatus:'LOCATION_PENDING'}}); res.json(x); }
export async function getDistributor(req,res){const x=await prisma.distributorDetails.findUnique({where:{userId:req.user.id}}); if(!x)return res.status(404).json({message:'Distributor details not found.'});res.json(x)}
export async function updateDistributor(req,res){return saveDistributor(req,res)}
export async function savePharmacy(req,res){const d=req.body; const x=await prisma.pharmacyDetails.upsert({where:{userId:req.user.id},create:{userId:req.user.id,pharmacyName:d.pharmacyName || d.businessName || '',gstNumber:d.gstNumber,drugLicenseNumber:d.drugLicenseNumber,drugLicenseExpiryDate:dateOrNull(d.drugLicenseExpiryDate),panNumber:d.panNumber,pharmacyRegistrationNumber:d.pharmacyRegistrationNumber,storeOpenTime:d.storeOpenTime,storeCloseTime:d.storeCloseTime,is24x7:Boolean(d.is24x7),emergencyContactNumber:d.emergencyContactNumber,contactPerson:d.contactPerson,contactNumber:d.contactNumber,email:d.email,formattedAddress:d.formattedAddress,latitude:d.latitude==null?null:Number(d.latitude),longitude:d.longitude==null?null:Number(d.longitude)},update:{pharmacyName:d.pharmacyName || d.businessName || '',gstNumber:d.gstNumber,drugLicenseNumber:d.drugLicenseNumber,drugLicenseExpiryDate:dateOrNull(d.drugLicenseExpiryDate),panNumber:d.panNumber,pharmacyRegistrationNumber:d.pharmacyRegistrationNumber,storeOpenTime:d.storeOpenTime,storeCloseTime:d.storeCloseTime,is24x7:Boolean(d.is24x7),emergencyContactNumber:d.emergencyContactNumber,contactPerson:d.contactPerson,contactNumber:d.contactNumber,email:d.email,formattedAddress:d.formattedAddress,latitude:d.latitude==null?null:Number(d.latitude),longitude:d.longitude==null?null:Number(d.longitude)}}); await prisma.user.update({where:{id:req.user.id},data:{onboardingStatus:'LOCATION_PENDING'}});res.json(x)}
export async function getPharmacy(req,res){const x=await prisma.pharmacyDetails.findUnique({where:{userId:req.user.id}});if(!x)return res.status(404).json({message:'Pharmacy details not found.'});res.json(x)}

export async function saveBank(req,res){const d=req.body;if(!d.accountHolderName||!d.accountNumber||!d.ifscCode)return res.status(400).json({message:'Account holder, account number and IFSC are required.'});if(d.confirmAccountNumber && d.accountNumber!==d.confirmAccountNumber)return res.status(400).json({message:'Account numbers do not match.'});const x=await prisma.bankDetails.upsert({where:{userId:req.user.id},create:{userId:req.user.id,accountHolderName:d.accountHolderName,bankName:d.bankName,accountNumber:d.accountNumber,ifscCode:String(d.ifscCode).toUpperCase(),branchName:d.branchName||d.branch,upiId:d.upiId,ifscVerified:Boolean(d.ifscVerified)},update:{accountHolderName:d.accountHolderName,bankName:d.bankName,accountNumber:d.accountNumber,ifscCode:String(d.ifscCode).toUpperCase(),branchName:d.branchName||d.branch,upiId:d.upiId,ifscVerified:Boolean(d.ifscVerified)}});await prisma.user.update({where:{id:req.user.id},data:{onboardingStatus:'REVIEW_PENDING'}});res.json({...x,accountNumber:'****'+x.accountNumber.slice(-4)})}
export async function getBank(req,res){const x=await prisma.bankDetails.findUnique({where:{userId:req.user.id}});if(!x)return res.status(404).json({message:'Bank details not found.'});res.json({...x,accountNumber:'****'+x.accountNumber.slice(-4)})}

export async function getStatus(req,res){const [locations,documents,dist,pharm,bank]=await Promise.all([prisma.businessLocation.count({where:{userId:req.user.id}}),prisma.document.count({where:{userId:req.user.id}}),prisma.distributorDetails.findUnique({where:{userId:req.user.id}}),prisma.pharmacyDetails.findUnique({where:{userId:req.user.id}}),prisma.bankDetails.findUnique({where:{userId:req.user.id}})]);res.json({user:publicUser(req.user),progress:{businessType:req.user.businessType!==null,businessDetails:Boolean(dist||pharm),location:locations>0,documents:documents>0,bank:Boolean(bank),plan:Boolean(req.user.selectedPlan),payment:Boolean(req.user.paymentMethod)}})}
export async function getSummary(req,res){const [locations,documents,dist,pharm,bank]=await Promise.all([prisma.businessLocation.findMany({where:{userId:req.user.id}}),prisma.document.findMany({where:{userId:req.user.id},select:{id:true,documentType:true,originalName:true,mimeType:true,size:true,createdAt:true,updatedAt:true}}),prisma.distributorDetails.findUnique({where:{userId:req.user.id}}),prisma.pharmacyDetails.findUnique({where:{userId:req.user.id}}),prisma.bankDetails.findUnique({where:{userId:req.user.id}})]);res.json({account:publicUser(req.user),business:dist||pharm,locations,documents,bank:bank?{...bank,accountNumber:'****'+bank.accountNumber.slice(-4)}:null,plan:req.user.selectedPlan||'Free',paymentMethod:req.user.paymentMethod||'Not selected'})}
export async function savePlan(req,res){const {selectedPlan,paymentMethod}=req.body;const u=await prisma.user.update({where:{id:req.user.id},data:{selectedPlan:selectedPlan||null,paymentMethod:paymentMethod||null}});res.json({selectedPlan:u.selectedPlan,paymentMethod:u.paymentMethod})}
export async function complete(req,res){const u=await prisma.user.update({where:{id:req.user.id},data:{onboardingStatus:'COMPLETE'}});res.json({message:'Onboarding completed.',user:publicUser(u)})}
