import { useEffect, useState } from 'react';
import { CheckCircle, XCircle, Eye, RefreshCw, ShieldCheck } from 'lucide-react';
import { getOnboardingApplications, getOnboardingApplication, approveOnboardingApplication, rejectOnboardingApplication } from '../../services/onboardingApprovalApi';

const money = n => n == null ? '—' : `₹${(Number(n)/100).toLocaleString('en-IN')}`;

export default function OnboardingApprovals(){
  const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[status,setStatus]=useState('pending'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const r=await getOnboardingApplications(status);setItems(r.items||[]);}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[status]);
  const open=async id=>{try{setSelected(await getOnboardingApplication(id));setNote('')}catch(e){setError(e.message)}};
  const approve=async()=>{if(!selected)return;if(!confirm('Approve this onboarding application and generate ERP credentials?'))return;setBusy(true);try{const r=await approveOnboardingApplication(selected.id,note);setSelected({...selected,...r});await load();}catch(e){setError(e.message)}finally{setBusy(false)}};
  const reject=async()=>{const reason=prompt('Enter rejection reason (minimum 5 characters):');if(!reason)return;setBusy(true);try{await rejectOnboardingApplication(selected.id,reason);setSelected(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="flex flex-col gap-6">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-[#171c24]">Onboarding Approvals</h1><p className="text-sm text-[#424751] mt-1">Review submitted pharmacy onboarding data. Credentials are generated only after approval.</p></div><button onClick={load} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-white border border-slate-200"><RefreshCw size={17}/> Refresh</button></div>
    <div className="flex gap-2">{['pending','approved','rejected','all'].map(x=><button key={x} onClick={()=>setStatus(x)} className={`px-4 py-2 rounded-lg text-sm font-semibold ${status===x?'bg-[#006d40] text-white':'bg-white border text-slate-600'}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
    {error&&<div className="rounded-xl bg-red-50 border border-red-200 p-3 text-sm text-red-700">{error}</div>}
    <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden"><div className="p-4 bg-slate-50 font-semibold">{loading?'Loading…':`${items.length} application(s)`}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="text-left p-3">Applicant</th><th className="text-left p-3">Business</th><th className="text-left p-3">Submitted</th><th className="text-left p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-t hover:bg-slate-50"><td className="p-3"><div className="font-semibold">{x.fullName}</div><div className="text-xs text-slate-500">{x.email}</div></td><td className="p-3">{x.businessType||'—'}</td><td className="p-3">{x.submittedAt?new Date(x.submittedAt).toLocaleString('en-IN'):'—'}</td><td className="p-3"><span className="px-2 py-1 rounded-full bg-slate-100">{x.status}</span></td><td className="p-3 text-center"><button onClick={()=>open(x.id)} className="p-2 rounded-lg bg-blue-50 text-blue-700"><Eye size={17}/></button></td></tr>)}{!loading&&!items.length&&<tr><td colSpan="5" className="p-10 text-center text-slate-500">No applications found.</td></tr>}</tbody></table></div></div>
    {selected&&<div className="fixed inset-0 bg-slate-950/40 z-50 flex justify-end"><div className="w-full max-w-2xl h-full bg-white overflow-y-auto p-6"><div className="flex justify-between items-center"><div><h2 className="text-xl font-bold">Application Review</h2><p className="text-xs text-slate-500">{selected.id}</p></div><button onClick={()=>setSelected(null)} className="text-slate-500">✕</button></div>
      <section className="mt-6 grid sm:grid-cols-2 gap-3">{[['Name',selected.fullName],['Email',selected.email],['Mobile',selected.mobileNumber],['Business Type',selected.businessType],['Application Status',selected.status],['Pharmacy ID',selected.pharmacyId||'Generated after approval'],['License',selected.licenseNumber||'Generated after approval']].map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 border p-3"><div className="text-xs text-slate-500">{k}</div><div className="font-semibold mt-1 break-all">{v||'—'}</div></div>)}</section>
      {selected.pharmacy&&<section className="mt-5"><h3 className="font-bold mb-2">Pharmacy Details</h3><pre className="text-xs whitespace-pre-wrap bg-slate-50 rounded-xl p-4">{JSON.stringify(selected.pharmacy,null,2)}</pre></section>}
      {selected.bank&&<section className="mt-5"><h3 className="font-bold mb-2">Bank Verification</h3><pre className="text-xs whitespace-pre-wrap bg-slate-50 rounded-xl p-4">{JSON.stringify(selected.bank,null,2)}</pre></section>}
      {selected.locations?.length>0&&<section className="mt-5"><h3 className="font-bold mb-2">Locations</h3><pre className="text-xs whitespace-pre-wrap bg-slate-50 rounded-xl p-4">{JSON.stringify(selected.locations,null,2)}</pre></section>}
      <section className="mt-5"><h3 className="font-bold mb-2">Documents</h3><div className="space-y-2">{(selected.documents||[]).map(d=><div key={d.id} className="p-3 rounded-xl border flex justify-between"><span>{d.fileName}</span><span className="text-xs text-slate-500">{d.status}</span></div>)}</div></section>
      {selected.payment&&<div className="mt-5 p-4 rounded-xl bg-emerald-50 border border-emerald-100"><div className="font-semibold">Verified Payment</div><div className="text-sm mt-1">{money(selected.payment.amountPaise)} · {selected.payment.paymentId}</div></div>}
      {selected.status==='pending'&&<><textarea value={note} onChange={e=>setNote(e.target.value)} rows="3" placeholder="Optional approval note" className="w-full mt-5 border rounded-xl p-3"/><div className="grid grid-cols-2 gap-3 mt-4"><button disabled={busy} onClick={approve} className="py-3 rounded-xl bg-[#006d40] text-white font-bold flex justify-center gap-2"><CheckCircle size={18}/> Approve & Generate Credentials</button><button disabled={busy} onClick={reject} className="py-3 rounded-xl bg-red-50 text-red-700 font-bold flex justify-center gap-2"><XCircle size={18}/> Reject</button></div></>}
      {selected.status==='approved'&&selected.erpUsername&&<div className="mt-5 p-5 rounded-2xl bg-emerald-50 border border-emerald-200"><div className="flex gap-2 items-center font-bold text-emerald-800"><ShieldCheck size={19}/> Credentials generated</div><div className="mt-3 text-sm">Username: <b>{selected.erpUsername}</b></div><div className="text-sm">Temporary password is delivered to the customer and is not displayed again here.</div></div>}
    </div></div>}
  </div>
}
